import heroHouse from "@/assets/hero-house.jpg";

export const agencyConfig = {
  brand: {
    name: "Signature Immobilier",
    logoInitial: "S",
    logoUrl: "",
    tagline: "Vendez votre bien avec clarté, suivi et sérénité.",
    positioning: "Plateforme de transparence immobilière",
  },
  contact: {
    email: "contact@signature-immobilier.fr",
    phone: "05 62 00 00 00",
    phoneHref: "tel:0562000000",
    address: "12 avenue Bertrand Barère",
    city: "65000 Tarbes",
    area: "Hautes-Pyrénées",
  },
  colors: {
    primary: "ink",
    accent: "gold",
    background: "ivory",
  },
  navigation: {
    public: [
      { to: "/", label: "Biens à vendre" },
      { to: "/diagnostic", label: "Estimation" },
      { to: "/mon-suivi", label: "Mon suivi" },
    ],
    primaryCta: { to: "/diagnostic", label: "Estimer mon bien" },
    secondaryCta: { href: "#biens-a-vendre", label: "Voir les biens" },
  },
  home: {
    eyebrow: "Biens à vendre dans les Hautes-Pyrénées",
    title: "Maisons et appartements suivis avec transparence.",
    intro:
      "Découvrez une sélection de biens locaux, puis demandez une estimation si vous souhaitez vendre avec un suivi clair du premier rendez-vous à la signature.",
    propertySectionTitle: "Biens à vendre",
    propertySectionText:
      "Une sélection courte, lisible et visuelle. Chaque bien présente l’essentiel sans surcharge.",
    trustTitle: "Pourquoi choisir cette agence ?",
    trustText:
      "Vendre un bien ne devrait pas être une période d’incertitude. Avec Signature Immobilier, chaque vendeur sait où en est sa vente, quelles visites sont prévues, quels retours ont été faits et quels documents sont disponibles.",
    trustCards: [
      {
        title: "Transparence",
        text: "Un espace vendeur clair pour suivre les étapes, les visites et les documents.",
      },
      {
        title: "Accompagnement",
        text: "Un conseiller référent garde le fil du projet du mandat jusqu’à la vente.",
      },
      {
        title: "Réactivité",
        text: "Les retours importants sont centralisés pour éviter les zones de flou.",
      },
    ],
    trackingTitle: "Le suivi Amazon de votre vente immobilière.",
    trackingText:
      "Le vendeur retrouve sa progression, les comptes-rendus de visite, ses documents et la prochaine étape sans devoir appeler l’agence pour savoir où ça en est.",
    trackingBullets: [
      "Progression de vente visible en un coup d’œil",
      "Comptes-rendus de visite centralisés",
      "Documents importants au même endroit",
      "Prochaine étape toujours claire",
    ],
    ctaTitle: "Vous souhaitez vendre votre bien ?",
    ctaText: "Demandez une estimation. Un conseiller vous rappelle rapidement.",
  },
  estimation: {
    title: "Demande d’estimation",
    subtitle:
      "Une question à la fois, pour transmettre à l’agence les informations utiles sans formulaire interminable.",
    finalTitle: "Votre demande a bien été transmise.",
    finalText:
      "Un conseiller vous rappelle rapidement pour échanger sur votre projet.",
    steps: [
      {
        title: "Quel type de bien souhaitez-vous vendre ?",
        description: "Choisissez la catégorie qui décrit le mieux votre bien.",
      },
      {
        title: "Où se situe le bien ?",
        description:
          "L’adresse permet à l’agence de préparer une première lecture locale.",
      },
      {
        title: "Quelle est la surface approximative ?",
        description:
          "Une estimation fiable commence par les volumes principaux.",
      },
      {
        title: "Quelques détails pour mieux comprendre votre bien",
        description:
          "Ces éléments aident l’agence à qualifier rapidement le projet.",
      },
      {
        title: "Avez-vous quelques photos ?",
        description:
          "Les photos permettent à l’agence de mieux préparer son estimation.",
      },
      {
        title: "Comment pouvons-nous vous recontacter ?",
        description:
          "Un conseiller vous rappellera rapidement. Aucun agenda automatique.",
      },
    ],
    propertyTypes: [
      "Maison",
      "Appartement",
      "Terrain",
      "Immeuble",
      "Local commercial",
    ],
    generalStates: ["Excellent", "Bon", "À rafraîchir", "Travaux à prévoir"],
  },
  saleProgress: [
    "Mandat signé",
    "Annonce publiée",
    "Visites en cours",
    "Offre reçue",
    "Compromis signé",
    "Vente finalisée",
  ],
  agents: [
    {
      id: "agent-sophie",
      name: "Sophie Martin",
      role: "Conseillère dédiée",
      phone: "05 62 00 00 00",
      phoneHref: "tel:0562000000",
      email: "sophie@signature-immobilier.fr",
      photo: "",
    },
    {
      id: "agent-julie",
      name: "Julie Martin",
      role: "Agent référent",
      phone: "05 62 00 00 01",
      phoneHref: "tel:0562000001",
      email: "julie@signature-immobilier.fr",
      photo: "",
    },
  ],
  properties: [
    {
      id: "maison-familiale-tarbes",
      title: "Maison familiale à Tarbes",
      type: "Maison",
      city: "Tarbes",
      address: "Quartier Arsenal",
      price: "325 000 €",
      surface: 115,
      rooms: 5,
      bedrooms: 4,
      bathrooms: 2,
      land: "Jardin clos 520 m²",
      dpe: "D",
      status: "Visites en cours",
      currentStep: "Visites en cours",
      coverImage: heroHouse,
      gallery: [heroHouse],
      agentId: "agent-sophie",
      sellerId: "seller-julien",
      nextVisit: "Jeudi 15 juin à 14h30",
      description:
        "Maison lumineuse proche des commodités, avec pièce de vie ouverte, jardin clos et quatre chambres. Un bien familial facile à projeter, idéal pour une résidence principale.",
      features: ["Jardin clos", "Garage", "Cuisine ouverte", "Quartier calme"],
      documents: [
        { name: "Diagnostics", status: "Disponible" },
        { name: "Plans", status: "Disponible" },
        { name: "Taxe foncière", status: "Nouveau" },
      ],
    },
    {
      id: "appartement-renove-bagneres",
      title: "Appartement rénové à Bagnères-de-Bigorre",
      type: "Appartement",
      city: "Bagnères-de-Bigorre",
      address: "Centre-ville",
      price: "178 000 €",
      surface: 67,
      rooms: 3,
      bedrooms: 2,
      bathrooms: 1,
      land: "Balcon",
      dpe: "C",
      status: "Annonce publiée",
      currentStep: "Annonce publiée",
      coverImage: heroHouse,
      gallery: [heroHouse],
      agentId: "agent-julie",
      sellerId: "seller-claire",
      nextVisit: "À planifier",
      description:
        "Appartement traversant en cœur de ville, rénové avec goût, faibles charges et balcon exposé sud. Une adresse simple à vivre au quotidien.",
      features: ["Balcon", "Faibles charges", "Rénové", "Centre-ville"],
      documents: [
        { name: "Diagnostics", status: "Disponible" },
        { name: "Règlement de copropriété", status: "Disponible" },
      ],
    },
    {
      id: "villa-jardin-lourdes",
      title: "Villa avec jardin à Lourdes",
      type: "Villa",
      city: "Lourdes",
      address: "Secteur Soum",
      price: "420 000 €",
      surface: 140,
      rooms: 6,
      bedrooms: 4,
      bathrooms: 2,
      land: "Terrain 850 m²",
      dpe: "C",
      status: "Offre reçue",
      currentStep: "Offre reçue",
      coverImage: heroHouse,
      gallery: [heroHouse],
      agentId: "agent-sophie",
      sellerId: "seller-marc",
      nextVisit: "Compte-rendu disponible",
      description:
        "Villa familiale avec grand jardin, garage double et volumes confortables. Le bien a reçu une offre après plusieurs visites qualifiées.",
      features: [
        "Grand terrain",
        "Garage double",
        "Suite parentale",
        "Vue dégagée",
      ],
      documents: [
        { name: "Diagnostics", status: "Disponible" },
        { name: "Offre d’achat", status: "Nouveau" },
      ],
    },
    {
      id: "immeuble-lannemezan",
      title: "Immeuble de rapport à Lannemezan",
      type: "Immeuble",
      city: "Lannemezan",
      address: "Proche gare",
      price: "295 000 €",
      surface: 210,
      rooms: 9,
      bedrooms: 6,
      bathrooms: 4,
      land: "Cour intérieure",
      dpe: "E",
      status: "Mandat signé",
      currentStep: "Mandat signé",
      coverImage: heroHouse,
      gallery: [heroHouse],
      agentId: "agent-julie",
      sellerId: "seller-paul",
      nextVisit: "Reportage photo prévu",
      description:
        "Immeuble de rapport avec plusieurs lots, cour intérieure et potentiel locatif. Dossier en préparation avant diffusion.",
      features: ["Plusieurs lots", "Cour", "Proche gare", "Potentiel locatif"],
      documents: [
        { name: "Mandat", status: "Disponible" },
        { name: "Diagnostics", status: "À venir" },
      ],
    },
    {
      id: "maison-village-vic",
      title: "Maison de village à Vic-en-Bigorre",
      type: "Maison",
      city: "Vic-en-Bigorre",
      address: "Centre ancien",
      price: "210 000 €",
      surface: 92,
      rooms: 4,
      bedrooms: 3,
      bathrooms: 1,
      land: "Patio",
      dpe: "D",
      status: "Annonce publiée",
      currentStep: "Annonce publiée",
      coverImage: heroHouse,
      gallery: [heroHouse],
      agentId: "agent-sophie",
      sellerId: "seller-anne",
      nextVisit: "Samedi 17 juin à 10h00",
      description:
        "Maison de village chaleureuse avec patio, séjour lumineux et trois chambres. Une base saine pour un projet principal ou secondaire.",
      features: ["Patio", "Centre ancien", "Trois chambres", "Charme ancien"],
      documents: [
        { name: "Diagnostics", status: "Disponible" },
        { name: "Mandat", status: "Disponible" },
      ],
    },
  ],
  sellers: [
    {
      id: "seller-julien",
      firstName: "Julien",
      lastName: "Marot",
      email: "julien.marot@example.com",
      phone: "06 00 00 00 01",
      propertyId: "maison-familiale-tarbes",
    },
    {
      id: "seller-claire",
      firstName: "Claire",
      lastName: "Lemoine",
      email: "claire.lemoine@example.com",
      phone: "06 00 00 00 02",
      propertyId: "appartement-renove-bagneres",
    },
    {
      id: "seller-marc",
      firstName: "Marc",
      lastName: "Berthier",
      email: "marc.berthier@example.com",
      phone: "06 00 00 00 04",
      propertyId: "villa-jardin-lourdes",
    },
  ],
  visits: [
    {
      id: "v1",
      propertyId: "maison-familiale-tarbes",
      bien: "Maison 115 m² - Tarbes",
      acheteur: "Famille Dubois",
      date: "Jeudi 15 juin à 14h30",
      interet: "fort" as const,
      apprecies: "Emplacement, luminosité, jardin",
      blocages: "Travaux cuisine à prévoir",
      financement: "en cours" as const,
      prochaine: "Relance sous 48h",
      resume:
        "Les visiteurs ont apprécié l’emplacement, la luminosité et le jardin. Leur principale hésitation concerne les travaux de cuisine. Leur financement est en cours de validation. Une relance est prévue sous 48 heures.",
    },
  ],
  documents: [
    "Mandat de vente",
    "Diagnostics",
    "Offre d’achat",
    "Compromis",
    "Documents complémentaires",
  ],
  testimonials: [
    {
      name: "Claire L.",
      text: "J’ai enfin su où en était la vente sans devoir relancer l’agence.",
    },
  ],
  prospects: [
    {
      id: "p1",
      prenom: "Julien",
      nom: "Marot",
      ville: "Tarbes",
      bien: "Maison 115 m²",
      surface: 115,
      type: "Maison",
      pieces: 5,
      delai: "1 à 3 mois",
      motivation: "Mutation professionnelle",
      score: "chaud" as const,
      action: "Rappeler aujourd’hui",
      peur: "Vendre trop vite à un prix bas",
      forts: ["Jardin clos", "Quartier recherché", "Lumineuse"],
      faibles: ["Cuisine à rafraîchir", "DPE D"],
      docs: ["Titre de propriété", "Taxe foncière", "DPE"],
      angle: "Sécuriser le prix de départ pour ne pas perdre 2 mois",
      script:
        "Bonjour Julien, j’ai bien reçu votre diagnostic vendeur. Ce qui ressort, c’est que votre projet semble assez avancé, notamment avec votre délai de 1 à 3 mois. Le point important maintenant, c’est de sécuriser le prix de départ pour éviter de perdre du temps ou de devoir baisser plus tard. Je vous propose qu’on regarde ensemble la stratégie la plus intelligente pour vendre dans les meilleures conditions.",
    },
    {
      id: "p2",
      prenom: "Claire",
      nom: "Lemoine",
      ville: "Bagnères-de-Bigorre",
      bien: "Appartement 67 m²",
      surface: 67,
      type: "Appartement",
      pieces: 3,
      delai: "Pas pressée",
      motivation: "Achat d’un autre bien",
      score: "tiede" as const,
      action: "Envoyer une première analyse",
      peur: "Choisir la mauvaise agence",
      forts: ["Centre-ville", "Balcon", "Faibles charges"],
      faibles: ["3e étage sans ascenseur"],
      docs: ["Charges de copropriété", "Règlement de copropriété"],
      angle: "Lui montrer la valeur d’un accompagnement long",
      script:
        "Bonjour Claire, suite à votre diagnostic, je vous envoie aujourd’hui une première analyse de votre appartement avec une fourchette de prix réaliste et la concurrence locale. L’idée n’est pas de vous presser, mais de vous donner une vision claire pour décider sereinement le moment venu.",
    },
    {
      id: "p3",
      prenom: "Marc",
      nom: "Berthier",
      ville: "Lourdes",
      bien: "Maison 140 m²",
      surface: 140,
      type: "Maison",
      pieces: 6,
      delai: "Urgent",
      motivation: "Séparation",
      score: "tres-chaud" as const,
      action: "Appeler sous 2 heures",
      peur: "Que la situation s’éternise",
      forts: ["Grand terrain", "Garage double", "Travaux récents"],
      faibles: ["Décoration personnelle marquée"],
      docs: ["Titre de propriété", "Factures de travaux"],
      angle: "Prendre en main rapidement et discrètement",
      script:
        "Bonjour Marc, je vous appelle suite à votre diagnostic. Je comprends que le contexte demande d’aller vite et avec discrétion. Mon rôle est de vous proposer une stratégie de vente claire, un calendrier serré et un seul interlocuteur du début à la fin. Je vous propose qu’on se voie rapidement, idéalement cette semaine.",
    },
  ],
} as const;

export type AgencyConfig = typeof agencyConfig;
export type Property = AgencyConfig["properties"][number];
export type Agent = AgencyConfig["agents"][number];
