/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultatRouteImport } from './routes/resultat'
import { Route as EspaceVendeurRouteImport } from './routes/espace-vendeur'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenceIndexRouteImport } from './routes/agence.index'
import { Route as AgenceCompteRenduRouteImport } from './routes/agence.compte-rendu'
import { Route as AgenceIdRouteImport } from './routes/agence.$id'

const ResultatRoute = ResultatRouteImport.update({
  id: '/resultat',
  path: '/resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceVendeurRoute = EspaceVendeurRouteImport.update({
  id: '/espace-vendeur',
  path: '/espace-vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceIndexRoute = AgenceIndexRouteImport.update({
  id: '/agence/',
  path: '/agence/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceCompteRenduRoute = AgenceCompteRenduRouteImport.update({
  id: '/agence/compte-rendu',
  path: '/agence/compte-rendu',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceIdRoute = AgenceIdRouteImport.update({
  id: '/agence/$id',
  path: '/agence/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/diagnostic': typeof DiagnosticRoute
  '/espace-vendeur': typeof EspaceVendeurRoute
  '/resultat': typeof ResultatRoute
  '/agence/$id': typeof AgenceIdRoute
  '/agence/compte-rendu': typeof AgenceCompteRenduRoute
  '/agence/': typeof AgenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/diagnostic': typeof DiagnosticRoute
  '/espace-vendeur': typeof EspaceVendeurRoute
  '/resultat': typeof ResultatRoute
  '/agence/$id': typeof AgenceIdRoute
  '/agence/compte-rendu': typeof AgenceCompteRenduRoute
  '/agence': typeof AgenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/diagnostic': typeof DiagnosticRoute
  '/espace-vendeur': typeof EspaceVendeurRoute
  '/resultat': typeof ResultatRoute
  '/agence/$id': typeof AgenceIdRoute
  '/agence/compte-rendu': typeof AgenceCompteRenduRoute
  '/agence/': typeof AgenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/diagnostic'
    | '/espace-vendeur'
    | '/resultat'
    | '/agence/$id'
    | '/agence/compte-rendu'
    | '/agence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/diagnostic'
    | '/espace-vendeur'
    | '/resultat'
    | '/agence/$id'
    | '/agence/compte-rendu'
    | '/agence'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/diagnostic'
    | '/espace-vendeur'
    | '/resultat'
    | '/agence/$id'
    | '/agence/compte-rendu'
    | '/agence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DiagnosticRoute: typeof DiagnosticRoute
  EspaceVendeurRoute: typeof EspaceVendeurRoute
  ResultatRoute: typeof ResultatRoute
  AgenceIdRoute: typeof AgenceIdRoute
  AgenceCompteRenduRoute: typeof AgenceCompteRenduRoute
  AgenceIndexRoute: typeof AgenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultat': {
      id: '/resultat'
      path: '/resultat'
      fullPath: '/resultat'
      preLoaderRoute: typeof ResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-vendeur': {
      id: '/espace-vendeur'
      path: '/espace-vendeur'
      fullPath: '/espace-vendeur'
      preLoaderRoute: typeof EspaceVendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/': {
      id: '/agence/'
      path: '/agence'
      fullPath: '/agence/'
      preLoaderRoute: typeof AgenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/compte-rendu': {
      id: '/agence/compte-rendu'
      path: '/agence/compte-rendu'
      fullPath: '/agence/compte-rendu'
      preLoaderRoute: typeof AgenceCompteRenduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/$id': {
      id: '/agence/$id'
      path: '/agence/$id'
      fullPath: '/agence/$id'
      preLoaderRoute: typeof AgenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DiagnosticRoute: DiagnosticRoute,
  EspaceVendeurRoute: EspaceVendeurRoute,
  ResultatRoute: ResultatRoute,
  AgenceIdRoute: AgenceIdRoute,
  AgenceCompteRenduRoute: AgenceCompteRenduRoute,
  AgenceIndexRoute: AgenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
