/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendeurRouteImport } from './routes/vendeur'
import { Route as SellerDashboardRouteImport } from './routes/seller-dashboard'
import { Route as ResultatRouteImport } from './routes/resultat'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MonSuiviRouteImport } from './routes/mon-suivi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EspaceVendeurRouteImport } from './routes/espace-vendeur'
import { Route as EspaceSignatureRouteImport } from './routes/espace-signature'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminAgenceRouteImport } from './routes/admin-agence'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivationVendeurRouteImport } from './routes/activation-vendeur'
import { Route as ActivationPatronRouteImport } from './routes/activation-patron'
import { Route as ActivationAgentRouteImport } from './routes/activation-agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenceIndexRouteImport } from './routes/agence.index'
import { Route as DemoAgenceSlugRouteImport } from './routes/demo-agence.$slug'
import { Route as CreerAccesTokenRouteImport } from './routes/creer-acces.$token'
import { Route as BiensPropertyIdRouteImport } from './routes/biens.$propertyId'
import { Route as AgenceCompteRenduRouteImport } from './routes/agence.compte-rendu'
import { Route as AgenceSlugRouteImport } from './routes/agence.$slug'
import { Route as DemoAgenceSlugVendeurRouteImport } from './routes/demo-agence.$slug.vendeur'
import { Route as DemoAgenceSlugPatronRouteImport } from './routes/demo-agence.$slug.patron'
import { Route as DemoAgenceSlugEstimationRouteImport } from './routes/demo-agence.$slug.estimation'
import { Route as DemoAgenceSlugAgentRouteImport } from './routes/demo-agence.$slug.agent'
import { Route as AgentPropertiesIdRouteImport } from './routes/agent.properties.$id'
import { Route as AgenceSlugSettingsRouteImport } from './routes/agence.$slug.settings'
import { Route as AgenceSlugEstimationsRouteImport } from './routes/agence.$slug.estimations'
import { Route as AgenceSlugEstimationRouteImport } from './routes/agence.$slug.estimation'
import { Route as AgenceSlugEquipeRouteImport } from './routes/agence.$slug.equipe'
import { Route as AgenceSlugDemandesVisitesRouteImport } from './routes/agence.$slug.demandes-visites'
import { Route as AdminAgenciesSlugRouteImport } from './routes/admin.agencies.$slug'
import { Route as AccesAgenceTokenRouteImport } from './routes/acces.agence.$token'
import { Route as AgenceSlugVendeurSellerTokenRouteImport } from './routes/agence.$slug.vendeur.$sellerToken'
import { Route as DemoAgenceSlugBiensPropertyIdGererRouteImport } from './routes/demo-agence.$slug.biens.$propertyId.gerer'
import { Route as AgenceSlugBiensPropertyIdGererRouteImport } from './routes/agence.$slug.biens.$propertyId.gerer'

const VendeurRoute = VendeurRouteImport.update({
  id: '/vendeur',
  path: '/vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller-dashboard',
  path: '/seller-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatRoute = ResultatRouteImport.update({
  id: '/resultat',
  path: '/resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MonSuiviRoute = MonSuiviRouteImport.update({
  id: '/mon-suivi',
  path: '/mon-suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceVendeurRoute = EspaceVendeurRouteImport.update({
  id: '/espace-vendeur',
  path: '/espace-vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceSignatureRoute = EspaceSignatureRouteImport.update({
  id: '/espace-signature',
  path: '/espace-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgenceRoute = AdminAgenceRouteImport.update({
  id: '/admin-agence',
  path: '/admin-agence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationVendeurRoute = ActivationVendeurRouteImport.update({
  id: '/activation-vendeur',
  path: '/activation-vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationPatronRoute = ActivationPatronRouteImport.update({
  id: '/activation-patron',
  path: '/activation-patron',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationAgentRoute = ActivationAgentRouteImport.update({
  id: '/activation-agent',
  path: '/activation-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceIndexRoute = AgenceIndexRouteImport.update({
  id: '/agence/',
  path: '/agence/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgenceSlugRoute = DemoAgenceSlugRouteImport.update({
  id: '/demo-agence/$slug',
  path: '/demo-agence/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreerAccesTokenRoute = CreerAccesTokenRouteImport.update({
  id: '/creer-acces/$token',
  path: '/creer-acces/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensPropertyIdRoute = BiensPropertyIdRouteImport.update({
  id: '/biens/$propertyId',
  path: '/biens/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceCompteRenduRoute = AgenceCompteRenduRouteImport.update({
  id: '/agence/compte-rendu',
  path: '/agence/compte-rendu',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceSlugRoute = AgenceSlugRouteImport.update({
  id: '/agence/$slug',
  path: '/agence/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgenceSlugVendeurRoute = DemoAgenceSlugVendeurRouteImport.update({
  id: '/vendeur',
  path: '/vendeur',
  getParentRoute: () => DemoAgenceSlugRoute,
} as any)
const DemoAgenceSlugPatronRoute = DemoAgenceSlugPatronRouteImport.update({
  id: '/patron',
  path: '/patron',
  getParentRoute: () => DemoAgenceSlugRoute,
} as any)
const DemoAgenceSlugEstimationRoute =
  DemoAgenceSlugEstimationRouteImport.update({
    id: '/estimation',
    path: '/estimation',
    getParentRoute: () => DemoAgenceSlugRoute,
  } as any)
const DemoAgenceSlugAgentRoute = DemoAgenceSlugAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DemoAgenceSlugRoute,
} as any)
const AgentPropertiesIdRoute = AgentPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AgentRoute,
} as any)
const AgenceSlugSettingsRoute = AgenceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgenceSlugRoute,
} as any)
const AgenceSlugEstimationsRoute = AgenceSlugEstimationsRouteImport.update({
  id: '/estimations',
  path: '/estimations',
  getParentRoute: () => AgenceSlugRoute,
} as any)
const AgenceSlugEstimationRoute = AgenceSlugEstimationRouteImport.update({
  id: '/estimation',
  path: '/estimation',
  getParentRoute: () => AgenceSlugRoute,
} as any)
const AgenceSlugEquipeRoute = AgenceSlugEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AgenceSlugRoute,
} as any)
const AgenceSlugDemandesVisitesRoute =
  AgenceSlugDemandesVisitesRouteImport.update({
    id: '/demandes-visites',
    path: '/demandes-visites',
    getParentRoute: () => AgenceSlugRoute,
  } as any)
const AdminAgenciesSlugRoute = AdminAgenciesSlugRouteImport.update({
  id: '/agencies/$slug',
  path: '/agencies/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AccesAgenceTokenRoute = AccesAgenceTokenRouteImport.update({
  id: '/acces/agence/$token',
  path: '/acces/agence/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceSlugVendeurSellerTokenRoute =
  AgenceSlugVendeurSellerTokenRouteImport.update({
    id: '/vendeur/$sellerToken',
    path: '/vendeur/$sellerToken',
    getParentRoute: () => AgenceSlugRoute,
  } as any)
const DemoAgenceSlugBiensPropertyIdGererRoute =
  DemoAgenceSlugBiensPropertyIdGererRouteImport.update({
    id: '/biens/$propertyId/gerer',
    path: '/biens/$propertyId/gerer',
    getParentRoute: () => DemoAgenceSlugRoute,
  } as any)
const AgenceSlugBiensPropertyIdGererRoute =
  AgenceSlugBiensPropertyIdGererRouteImport.update({
    id: '/biens/$propertyId/gerer',
    path: '/biens/$propertyId/gerer',
    getParentRoute: () => AgenceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation-agent': typeof ActivationAgentRoute
  '/activation-patron': typeof ActivationPatronRoute
  '/activation-vendeur': typeof ActivationVendeurRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-agence': typeof AdminAgenceRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent-dashboard': typeof AgentDashboardRoute
  '/demo': typeof DemoRoute
  '/diagnostic': typeof DiagnosticRoute
  '/espace-signature': typeof EspaceSignatureRoute
  '/espace-vendeur': typeof EspaceVendeurRoute
  '/login': typeof LoginRoute
  '/mon-suivi': typeof MonSuiviRoute
  '/register': typeof RegisterRoute
  '/resultat': typeof ResultatRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/vendeur': typeof VendeurRoute
  '/agence/$slug': typeof AgenceSlugRouteWithChildren
  '/agence/compte-rendu': typeof AgenceCompteRenduRoute
  '/biens/$propertyId': typeof BiensPropertyIdRoute
  '/creer-acces/$token': typeof CreerAccesTokenRoute
  '/demo-agence/$slug': typeof DemoAgenceSlugRouteWithChildren
  '/agence/': typeof AgenceIndexRoute
  '/acces/agence/$token': typeof AccesAgenceTokenRoute
  '/admin/agencies/$slug': typeof AdminAgenciesSlugRoute
  '/agence/$slug/demandes-visites': typeof AgenceSlugDemandesVisitesRoute
  '/agence/$slug/equipe': typeof AgenceSlugEquipeRoute
  '/agence/$slug/estimation': typeof AgenceSlugEstimationRoute
  '/agence/$slug/estimations': typeof AgenceSlugEstimationsRoute
  '/agence/$slug/settings': typeof AgenceSlugSettingsRoute
  '/agent/properties/$id': typeof AgentPropertiesIdRoute
  '/demo-agence/$slug/agent': typeof DemoAgenceSlugAgentRoute
  '/demo-agence/$slug/estimation': typeof DemoAgenceSlugEstimationRoute
  '/demo-agence/$slug/patron': typeof DemoAgenceSlugPatronRoute
  '/demo-agence/$slug/vendeur': typeof DemoAgenceSlugVendeurRoute
  '/agence/$slug/vendeur/$sellerToken': typeof AgenceSlugVendeurSellerTokenRoute
  '/agence/$slug/biens/$propertyId/gerer': typeof AgenceSlugBiensPropertyIdGererRoute
  '/demo-agence/$slug/biens/$propertyId/gerer': typeof DemoAgenceSlugBiensPropertyIdGererRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation-agent': typeof ActivationAgentRoute
  '/activation-patron': typeof ActivationPatronRoute
  '/activation-vendeur': typeof ActivationVendeurRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-agence': typeof AdminAgenceRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent-dashboard': typeof AgentDashboardRoute
  '/demo': typeof DemoRoute
  '/diagnostic': typeof DiagnosticRoute
  '/espace-signature': typeof EspaceSignatureRoute
  '/espace-vendeur': typeof EspaceVendeurRoute
  '/login': typeof LoginRoute
  '/mon-suivi': typeof MonSuiviRoute
  '/register': typeof RegisterRoute
  '/resultat': typeof ResultatRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/vendeur': typeof VendeurRoute
  '/agence/$slug': typeof AgenceSlugRouteWithChildren
  '/agence/compte-rendu': typeof AgenceCompteRenduRoute
  '/biens/$propertyId': typeof BiensPropertyIdRoute
  '/creer-acces/$token': typeof CreerAccesTokenRoute
  '/demo-agence/$slug': typeof DemoAgenceSlugRouteWithChildren
  '/agence': typeof AgenceIndexRoute
  '/acces/agence/$token': typeof AccesAgenceTokenRoute
  '/admin/agencies/$slug': typeof AdminAgenciesSlugRoute
  '/agence/$slug/demandes-visites': typeof AgenceSlugDemandesVisitesRoute
  '/agence/$slug/equipe': typeof AgenceSlugEquipeRoute
  '/agence/$slug/estimation': typeof AgenceSlugEstimationRoute
  '/agence/$slug/estimations': typeof AgenceSlugEstimationsRoute
  '/agence/$slug/settings': typeof AgenceSlugSettingsRoute
  '/agent/properties/$id': typeof AgentPropertiesIdRoute
  '/demo-agence/$slug/agent': typeof DemoAgenceSlugAgentRoute
  '/demo-agence/$slug/estimation': typeof DemoAgenceSlugEstimationRoute
  '/demo-agence/$slug/patron': typeof DemoAgenceSlugPatronRoute
  '/demo-agence/$slug/vendeur': typeof DemoAgenceSlugVendeurRoute
  '/agence/$slug/vendeur/$sellerToken': typeof AgenceSlugVendeurSellerTokenRoute
  '/agence/$slug/biens/$propertyId/gerer': typeof AgenceSlugBiensPropertyIdGererRoute
  '/demo-agence/$slug/biens/$propertyId/gerer': typeof DemoAgenceSlugBiensPropertyIdGererRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation-agent': typeof ActivationAgentRoute
  '/activation-patron': typeof ActivationPatronRoute
  '/activation-vendeur': typeof ActivationVendeurRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-agence': typeof AdminAgenceRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent-dashboard': typeof AgentDashboardRoute
  '/demo': typeof DemoRoute
  '/diagnostic': typeof DiagnosticRoute
  '/espace-signature': typeof EspaceSignatureRoute
  '/espace-vendeur': typeof EspaceVendeurRoute
  '/login': typeof LoginRoute
  '/mon-suivi': typeof MonSuiviRoute
  '/register': typeof RegisterRoute
  '/resultat': typeof ResultatRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/vendeur': typeof VendeurRoute
  '/agence/$slug': typeof AgenceSlugRouteWithChildren
  '/agence/compte-rendu': typeof AgenceCompteRenduRoute
  '/biens/$propertyId': typeof BiensPropertyIdRoute
  '/creer-acces/$token': typeof CreerAccesTokenRoute
  '/demo-agence/$slug': typeof DemoAgenceSlugRouteWithChildren
  '/agence/': typeof AgenceIndexRoute
  '/acces/agence/$token': typeof AccesAgenceTokenRoute
  '/admin/agencies/$slug': typeof AdminAgenciesSlugRoute
  '/agence/$slug/demandes-visites': typeof AgenceSlugDemandesVisitesRoute
  '/agence/$slug/equipe': typeof AgenceSlugEquipeRoute
  '/agence/$slug/estimation': typeof AgenceSlugEstimationRoute
  '/agence/$slug/estimations': typeof AgenceSlugEstimationsRoute
  '/agence/$slug/settings': typeof AgenceSlugSettingsRoute
  '/agent/properties/$id': typeof AgentPropertiesIdRoute
  '/demo-agence/$slug/agent': typeof DemoAgenceSlugAgentRoute
  '/demo-agence/$slug/estimation': typeof DemoAgenceSlugEstimationRoute
  '/demo-agence/$slug/patron': typeof DemoAgenceSlugPatronRoute
  '/demo-agence/$slug/vendeur': typeof DemoAgenceSlugVendeurRoute
  '/agence/$slug/vendeur/$sellerToken': typeof AgenceSlugVendeurSellerTokenRoute
  '/agence/$slug/biens/$propertyId/gerer': typeof AgenceSlugBiensPropertyIdGererRoute
  '/demo-agence/$slug/biens/$propertyId/gerer': typeof DemoAgenceSlugBiensPropertyIdGererRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation-agent'
    | '/activation-patron'
    | '/activation-vendeur'
    | '/admin'
    | '/admin-agence'
    | '/agent'
    | '/agent-dashboard'
    | '/demo'
    | '/diagnostic'
    | '/espace-signature'
    | '/espace-vendeur'
    | '/login'
    | '/mon-suivi'
    | '/register'
    | '/resultat'
    | '/seller-dashboard'
    | '/vendeur'
    | '/agence/$slug'
    | '/agence/compte-rendu'
    | '/biens/$propertyId'
    | '/creer-acces/$token'
    | '/demo-agence/$slug'
    | '/agence/'
    | '/acces/agence/$token'
    | '/admin/agencies/$slug'
    | '/agence/$slug/demandes-visites'
    | '/agence/$slug/equipe'
    | '/agence/$slug/estimation'
    | '/agence/$slug/estimations'
    | '/agence/$slug/settings'
    | '/agent/properties/$id'
    | '/demo-agence/$slug/agent'
    | '/demo-agence/$slug/estimation'
    | '/demo-agence/$slug/patron'
    | '/demo-agence/$slug/vendeur'
    | '/agence/$slug/vendeur/$sellerToken'
    | '/agence/$slug/biens/$propertyId/gerer'
    | '/demo-agence/$slug/biens/$propertyId/gerer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation-agent'
    | '/activation-patron'
    | '/activation-vendeur'
    | '/admin'
    | '/admin-agence'
    | '/agent'
    | '/agent-dashboard'
    | '/demo'
    | '/diagnostic'
    | '/espace-signature'
    | '/espace-vendeur'
    | '/login'
    | '/mon-suivi'
    | '/register'
    | '/resultat'
    | '/seller-dashboard'
    | '/vendeur'
    | '/agence/$slug'
    | '/agence/compte-rendu'
    | '/biens/$propertyId'
    | '/creer-acces/$token'
    | '/demo-agence/$slug'
    | '/agence'
    | '/acces/agence/$token'
    | '/admin/agencies/$slug'
    | '/agence/$slug/demandes-visites'
    | '/agence/$slug/equipe'
    | '/agence/$slug/estimation'
    | '/agence/$slug/estimations'
    | '/agence/$slug/settings'
    | '/agent/properties/$id'
    | '/demo-agence/$slug/agent'
    | '/demo-agence/$slug/estimation'
    | '/demo-agence/$slug/patron'
    | '/demo-agence/$slug/vendeur'
    | '/agence/$slug/vendeur/$sellerToken'
    | '/agence/$slug/biens/$propertyId/gerer'
    | '/demo-agence/$slug/biens/$propertyId/gerer'
  id:
    | '__root__'
    | '/'
    | '/activation-agent'
    | '/activation-patron'
    | '/activation-vendeur'
    | '/admin'
    | '/admin-agence'
    | '/agent'
    | '/agent-dashboard'
    | '/demo'
    | '/diagnostic'
    | '/espace-signature'
    | '/espace-vendeur'
    | '/login'
    | '/mon-suivi'
    | '/register'
    | '/resultat'
    | '/seller-dashboard'
    | '/vendeur'
    | '/agence/$slug'
    | '/agence/compte-rendu'
    | '/biens/$propertyId'
    | '/creer-acces/$token'
    | '/demo-agence/$slug'
    | '/agence/'
    | '/acces/agence/$token'
    | '/admin/agencies/$slug'
    | '/agence/$slug/demandes-visites'
    | '/agence/$slug/equipe'
    | '/agence/$slug/estimation'
    | '/agence/$slug/estimations'
    | '/agence/$slug/settings'
    | '/agent/properties/$id'
    | '/demo-agence/$slug/agent'
    | '/demo-agence/$slug/estimation'
    | '/demo-agence/$slug/patron'
    | '/demo-agence/$slug/vendeur'
    | '/agence/$slug/vendeur/$sellerToken'
    | '/agence/$slug/biens/$propertyId/gerer'
    | '/demo-agence/$slug/biens/$propertyId/gerer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationAgentRoute: typeof ActivationAgentRoute
  ActivationPatronRoute: typeof ActivationPatronRoute
  ActivationVendeurRoute: typeof ActivationVendeurRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminAgenceRoute: typeof AdminAgenceRoute
  AgentRoute: typeof AgentRouteWithChildren
  AgentDashboardRoute: typeof AgentDashboardRoute
  DemoRoute: typeof DemoRoute
  DiagnosticRoute: typeof DiagnosticRoute
  EspaceSignatureRoute: typeof EspaceSignatureRoute
  EspaceVendeurRoute: typeof EspaceVendeurRoute
  LoginRoute: typeof LoginRoute
  MonSuiviRoute: typeof MonSuiviRoute
  RegisterRoute: typeof RegisterRoute
  ResultatRoute: typeof ResultatRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  VendeurRoute: typeof VendeurRoute
  AgenceSlugRoute: typeof AgenceSlugRouteWithChildren
  AgenceCompteRenduRoute: typeof AgenceCompteRenduRoute
  BiensPropertyIdRoute: typeof BiensPropertyIdRoute
  CreerAccesTokenRoute: typeof CreerAccesTokenRoute
  DemoAgenceSlugRoute: typeof DemoAgenceSlugRouteWithChildren
  AgenceIndexRoute: typeof AgenceIndexRoute
  AccesAgenceTokenRoute: typeof AccesAgenceTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendeur': {
      id: '/vendeur'
      path: '/vendeur'
      fullPath: '/vendeur'
      preLoaderRoute: typeof VendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-dashboard': {
      id: '/seller-dashboard'
      path: '/seller-dashboard'
      fullPath: '/seller-dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultat': {
      id: '/resultat'
      path: '/resultat'
      fullPath: '/resultat'
      preLoaderRoute: typeof ResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-suivi': {
      id: '/mon-suivi'
      path: '/mon-suivi'
      fullPath: '/mon-suivi'
      preLoaderRoute: typeof MonSuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-vendeur': {
      id: '/espace-vendeur'
      path: '/espace-vendeur'
      fullPath: '/espace-vendeur'
      preLoaderRoute: typeof EspaceVendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-signature': {
      id: '/espace-signature'
      path: '/espace-signature'
      fullPath: '/espace-signature'
      preLoaderRoute: typeof EspaceSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-agence': {
      id: '/admin-agence'
      path: '/admin-agence'
      fullPath: '/admin-agence'
      preLoaderRoute: typeof AdminAgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-vendeur': {
      id: '/activation-vendeur'
      path: '/activation-vendeur'
      fullPath: '/activation-vendeur'
      preLoaderRoute: typeof ActivationVendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-patron': {
      id: '/activation-patron'
      path: '/activation-patron'
      fullPath: '/activation-patron'
      preLoaderRoute: typeof ActivationPatronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-agent': {
      id: '/activation-agent'
      path: '/activation-agent'
      fullPath: '/activation-agent'
      preLoaderRoute: typeof ActivationAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/': {
      id: '/agence/'
      path: '/agence'
      fullPath: '/agence/'
      preLoaderRoute: typeof AgenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-agence/$slug': {
      id: '/demo-agence/$slug'
      path: '/demo-agence/$slug'
      fullPath: '/demo-agence/$slug'
      preLoaderRoute: typeof DemoAgenceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creer-acces/$token': {
      id: '/creer-acces/$token'
      path: '/creer-acces/$token'
      fullPath: '/creer-acces/$token'
      preLoaderRoute: typeof CreerAccesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/$propertyId': {
      id: '/biens/$propertyId'
      path: '/biens/$propertyId'
      fullPath: '/biens/$propertyId'
      preLoaderRoute: typeof BiensPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/compte-rendu': {
      id: '/agence/compte-rendu'
      path: '/agence/compte-rendu'
      fullPath: '/agence/compte-rendu'
      preLoaderRoute: typeof AgenceCompteRenduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/$slug': {
      id: '/agence/$slug'
      path: '/agence/$slug'
      fullPath: '/agence/$slug'
      preLoaderRoute: typeof AgenceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-agence/$slug/vendeur': {
      id: '/demo-agence/$slug/vendeur'
      path: '/vendeur'
      fullPath: '/demo-agence/$slug/vendeur'
      preLoaderRoute: typeof DemoAgenceSlugVendeurRouteImport
      parentRoute: typeof DemoAgenceSlugRoute
    }
    '/demo-agence/$slug/patron': {
      id: '/demo-agence/$slug/patron'
      path: '/patron'
      fullPath: '/demo-agence/$slug/patron'
      preLoaderRoute: typeof DemoAgenceSlugPatronRouteImport
      parentRoute: typeof DemoAgenceSlugRoute
    }
    '/demo-agence/$slug/estimation': {
      id: '/demo-agence/$slug/estimation'
      path: '/estimation'
      fullPath: '/demo-agence/$slug/estimation'
      preLoaderRoute: typeof DemoAgenceSlugEstimationRouteImport
      parentRoute: typeof DemoAgenceSlugRoute
    }
    '/demo-agence/$slug/agent': {
      id: '/demo-agence/$slug/agent'
      path: '/agent'
      fullPath: '/demo-agence/$slug/agent'
      preLoaderRoute: typeof DemoAgenceSlugAgentRouteImport
      parentRoute: typeof DemoAgenceSlugRoute
    }
    '/agent/properties/$id': {
      id: '/agent/properties/$id'
      path: '/properties/$id'
      fullPath: '/agent/properties/$id'
      preLoaderRoute: typeof AgentPropertiesIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agence/$slug/settings': {
      id: '/agence/$slug/settings'
      path: '/settings'
      fullPath: '/agence/$slug/settings'
      preLoaderRoute: typeof AgenceSlugSettingsRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
    '/agence/$slug/estimations': {
      id: '/agence/$slug/estimations'
      path: '/estimations'
      fullPath: '/agence/$slug/estimations'
      preLoaderRoute: typeof AgenceSlugEstimationsRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
    '/agence/$slug/estimation': {
      id: '/agence/$slug/estimation'
      path: '/estimation'
      fullPath: '/agence/$slug/estimation'
      preLoaderRoute: typeof AgenceSlugEstimationRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
    '/agence/$slug/equipe': {
      id: '/agence/$slug/equipe'
      path: '/equipe'
      fullPath: '/agence/$slug/equipe'
      preLoaderRoute: typeof AgenceSlugEquipeRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
    '/agence/$slug/demandes-visites': {
      id: '/agence/$slug/demandes-visites'
      path: '/demandes-visites'
      fullPath: '/agence/$slug/demandes-visites'
      preLoaderRoute: typeof AgenceSlugDemandesVisitesRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
    '/admin/agencies/$slug': {
      id: '/admin/agencies/$slug'
      path: '/agencies/$slug'
      fullPath: '/admin/agencies/$slug'
      preLoaderRoute: typeof AdminAgenciesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/acces/agence/$token': {
      id: '/acces/agence/$token'
      path: '/acces/agence/$token'
      fullPath: '/acces/agence/$token'
      preLoaderRoute: typeof AccesAgenceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence/$slug/vendeur/$sellerToken': {
      id: '/agence/$slug/vendeur/$sellerToken'
      path: '/vendeur/$sellerToken'
      fullPath: '/agence/$slug/vendeur/$sellerToken'
      preLoaderRoute: typeof AgenceSlugVendeurSellerTokenRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
    '/demo-agence/$slug/biens/$propertyId/gerer': {
      id: '/demo-agence/$slug/biens/$propertyId/gerer'
      path: '/biens/$propertyId/gerer'
      fullPath: '/demo-agence/$slug/biens/$propertyId/gerer'
      preLoaderRoute: typeof DemoAgenceSlugBiensPropertyIdGererRouteImport
      parentRoute: typeof DemoAgenceSlugRoute
    }
    '/agence/$slug/biens/$propertyId/gerer': {
      id: '/agence/$slug/biens/$propertyId/gerer'
      path: '/biens/$propertyId/gerer'
      fullPath: '/agence/$slug/biens/$propertyId/gerer'
      preLoaderRoute: typeof AgenceSlugBiensPropertyIdGererRouteImport
      parentRoute: typeof AgenceSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgenciesSlugRoute: typeof AdminAgenciesSlugRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesSlugRoute: AdminAgenciesSlugRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentPropertiesIdRoute: typeof AgentPropertiesIdRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentPropertiesIdRoute: AgentPropertiesIdRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface AgenceSlugRouteChildren {
  AgenceSlugDemandesVisitesRoute: typeof AgenceSlugDemandesVisitesRoute
  AgenceSlugEquipeRoute: typeof AgenceSlugEquipeRoute
  AgenceSlugEstimationRoute: typeof AgenceSlugEstimationRoute
  AgenceSlugEstimationsRoute: typeof AgenceSlugEstimationsRoute
  AgenceSlugSettingsRoute: typeof AgenceSlugSettingsRoute
  AgenceSlugVendeurSellerTokenRoute: typeof AgenceSlugVendeurSellerTokenRoute
  AgenceSlugBiensPropertyIdGererRoute: typeof AgenceSlugBiensPropertyIdGererRoute
}

const AgenceSlugRouteChildren: AgenceSlugRouteChildren = {
  AgenceSlugDemandesVisitesRoute: AgenceSlugDemandesVisitesRoute,
  AgenceSlugEquipeRoute: AgenceSlugEquipeRoute,
  AgenceSlugEstimationRoute: AgenceSlugEstimationRoute,
  AgenceSlugEstimationsRoute: AgenceSlugEstimationsRoute,
  AgenceSlugSettingsRoute: AgenceSlugSettingsRoute,
  AgenceSlugVendeurSellerTokenRoute: AgenceSlugVendeurSellerTokenRoute,
  AgenceSlugBiensPropertyIdGererRoute: AgenceSlugBiensPropertyIdGererRoute,
}

const AgenceSlugRouteWithChildren = AgenceSlugRoute._addFileChildren(
  AgenceSlugRouteChildren,
)

interface DemoAgenceSlugRouteChildren {
  DemoAgenceSlugAgentRoute: typeof DemoAgenceSlugAgentRoute
  DemoAgenceSlugEstimationRoute: typeof DemoAgenceSlugEstimationRoute
  DemoAgenceSlugPatronRoute: typeof DemoAgenceSlugPatronRoute
  DemoAgenceSlugVendeurRoute: typeof DemoAgenceSlugVendeurRoute
  DemoAgenceSlugBiensPropertyIdGererRoute: typeof DemoAgenceSlugBiensPropertyIdGererRoute
}

const DemoAgenceSlugRouteChildren: DemoAgenceSlugRouteChildren = {
  DemoAgenceSlugAgentRoute: DemoAgenceSlugAgentRoute,
  DemoAgenceSlugEstimationRoute: DemoAgenceSlugEstimationRoute,
  DemoAgenceSlugPatronRoute: DemoAgenceSlugPatronRoute,
  DemoAgenceSlugVendeurRoute: DemoAgenceSlugVendeurRoute,
  DemoAgenceSlugBiensPropertyIdGererRoute:
    DemoAgenceSlugBiensPropertyIdGererRoute,
}

const DemoAgenceSlugRouteWithChildren = DemoAgenceSlugRoute._addFileChildren(
  DemoAgenceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationAgentRoute: ActivationAgentRoute,
  ActivationPatronRoute: ActivationPatronRoute,
  ActivationVendeurRoute: ActivationVendeurRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminAgenceRoute: AdminAgenceRoute,
  AgentRoute: AgentRouteWithChildren,
  AgentDashboardRoute: AgentDashboardRoute,
  DemoRoute: DemoRoute,
  DiagnosticRoute: DiagnosticRoute,
  EspaceSignatureRoute: EspaceSignatureRoute,
  EspaceVendeurRoute: EspaceVendeurRoute,
  LoginRoute: LoginRoute,
  MonSuiviRoute: MonSuiviRoute,
  RegisterRoute: RegisterRoute,
  ResultatRoute: ResultatRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  VendeurRoute: VendeurRoute,
  AgenceSlugRoute: AgenceSlugRouteWithChildren,
  AgenceCompteRenduRoute: AgenceCompteRenduRoute,
  BiensPropertyIdRoute: BiensPropertyIdRoute,
  CreerAccesTokenRoute: CreerAccesTokenRoute,
  DemoAgenceSlugRoute: DemoAgenceSlugRouteWithChildren,
  AgenceIndexRoute: AgenceIndexRoute,
  AccesAgenceTokenRoute: AccesAgenceTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
